### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Shallow2000** [miranheo/GenVIS#1]
Thanks for your excellent work! I wonder when you will release the code.

**Comment by miranheo** [comment]
Hi @Shallow2000,

Thank you for your interest!
I am expecting it to be in December.

**Comment by Shallow2000** [comment]
OK. Thank you! Look forward to your release!!!

**Comment by miranheo** [comment]
Thank you for your patience.
Feel free to email me if you have any questions :) - miran@yonsei.ac.kr
