### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by Shallow2000** [miranheo/GenVIS#2]
Thanks for your excellent work! When I read the implementation details in your paper, I am a little confused. Do you mean that GenVIS uses the finally trained model of VITA and then trains the proposed module? (It still consumes a lot of resources when training the VIS model.)

**Comment by miranheo** [comment]
Thank you for your question and sorry for the late reply.

Yes, for the best performance reported in the paper, GenVIS currently uses the finally trained model for VITA.
However, as long as the image level detector (e.g., Mask2Former) is trained in the target VIS domain, any type of weight may be used.
We would like to point out that in this case the performance reported in the paper is not guaranteed.
