### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by hekaijie123** [miranheo/GenVIS#3]
Dear Author, you said you would release the code in December, but now it is January.

**Comment by hekaijie123** [comment]
@miranheo

**Comment by Polaris-sh** [comment]
@miranheo Dear Author

**Comment by miranheo** [comment]
@hekaijie123 @Polaris-sh 

We appologize for the delay.
We are working on it and our team's current plan is to release the code after the reviewing process, which ends in a few weeks.
We appreciate your patience and interest in our work!

**Comment by miranheo** [comment]
@hekaijie123 @Polaris-sh 

Hi all, please check the released code. 
Additional checkpoints will be available soon! Thank you :)
