### ISSUE TITLE
About training using only youtube dataset.

### ISSUE THREAD

**Issue by hekaijie123** [miranheo/GenVIS#4]
Dear author. I was very curious that GenVIS was trained only with youtebe2019 and not with COCO dataset. What will the test result be? What should the training configs be changed to?

**Comment by hekaijie123** [comment]
@sukjunhwang @miranheo  
Excuse me.

**Comment by miranheo** [comment]
Thank you for your question!

In the case of YouTube 2019, I would say that the performance difference will not be large even if COCO is not used.
We plan to release configurations including training schedule that do not use the COCO dataset.
