### ISSUE TITLE
A question about data sampling.

### ISSUE THREAD

**Issue by pixeli99** [miranheo/GenVIS#5]
Hi,
[sukjunhwang](https://github.com/miranheo/GenVIS/commits?author=sukjunhwang)，

Thanks for your excellent work!

I noticed that for GenVIS, `SAMPLING_ FRAME_ SHUFFLE` is false, which means that the **frame id** to be sampled is orderly. For clip training, there may be duplicate images in a clip, and the probability is high. Is there a problem with such sampling?

**Comment by sukjunhwang** [comment]
Hi @pixeli99,

As GenVIS is designed to learn the sequential characteristics of videos, we set ```SAMPLING_FRAME_SHUFFLE``` to be false.
Yes, there can be a number of cases that a sampled clip hold duplicated frames, but we find it does not significantly affect the training.

Thank you

**Comment by pixeli99** [comment]
I see. Thank you very much for your reply.
