### ISSUE TITLE
about training time

### ISSUE THREAD

**Issue by pixeli99** [miranheo/GenVIS#7]
I would like to ask how long it will take for Genvis to train on Ovis, that is, to fully follow `genvis_R50_bs8_online.yaml`, 

On the four A100 gpus, it shows that it will take about 28 hours, and I am not sure if this is normal

**Comment by miranheo** [comment]
Hi,

I checked it on our server with 4 A100 GPUs, and it shows eta about ~25 hours after some warm-up iterations. 

Thank you :)

**Comment by miranheo** [comment]
The internal for loop iteration for sequence processing affects the learning speed.

**Comment by pixeli99** [comment]
thanks a lot!
